/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sisfo_Penjualan_pulsa;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class form_members extends javax.swing.JFrame {

    /**
     * Creates new form form_pulsa
     */
    public form_members() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        itmtelkom = new javax.swing.JMenuItem();
        itmtri = new javax.swing.JMenuItem();
        itmclose = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itmriwayat = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        jMenu4.setText("Pulsa Data & Reguler");

        itmtelkom.setText("Telkomsel");
        itmtelkom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmtelkomActionPerformed(evt);
            }
        });
        jMenu4.add(itmtelkom);

        itmtri.setText("Tri");
        itmtri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmtriActionPerformed(evt);
            }
        });
        jMenu4.add(itmtri);

        jMenu1.add(jMenu4);

        itmclose.setText("Close");
        itmclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmcloseActionPerformed(evt);
            }
        });
        jMenu1.add(itmclose);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        itmriwayat.setText("Riwayat");
        itmriwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmriwayatActionPerformed(evt);
            }
        });
        jMenu2.add(itmriwayat);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("About");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(738, 454));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itmtriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmtriActionPerformed
        form_pulsaTRI tri = new form_pulsaTRI();
        tri.show();
    }//GEN-LAST:event_itmtriActionPerformed

    private void itmtelkomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmtelkomActionPerformed
       form_pulsaTelkomsel telkom = new form_pulsaTelkomsel();
       telkom.show();
    }//GEN-LAST:event_itmtelkomActionPerformed

    private void itmcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmcloseActionPerformed
        this.dispose();
        new login().setVisible(true);
    }//GEN-LAST:event_itmcloseActionPerformed

    private void itmriwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmriwayatActionPerformed
        form_riwayat rw = new form_riwayat();
        rw.show();
    }//GEN-LAST:event_itmriwayatActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        JOptionPane.showMessageDialog(null, "CREATED BY 181021 Kalvin Ryan Duma Lumiling\n"+"Form Members");
   
    }//GEN-LAST:event_jMenu3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_members.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_members.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_members.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_members.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_members().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmclose;
    private javax.swing.JMenuItem itmriwayat;
    private javax.swing.JMenuItem itmtelkom;
    private javax.swing.JMenuItem itmtri;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables
}
